version: '3.1'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - 5678:5678
    environment:
      - GENERIC_TIMEZONE=America/Edmonton
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
      - N8N_HOST=localhost
      - N8N_PORT=5678
    volumes:
      - ./n8n-data:/home/node/.n8n 