version: '3.1'

services:
  n8n:
    build: .
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - GENERIC_TIMEZONE=America/Edmonton
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./scrape:/home/node/scrape